// <auto-generated />
using System;
using HospitalManagement.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagement.DataAccess.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260812111202_SekreterVeRandevuGuncellemeleri")]
    partial class SekreterVeRandevuGuncellemeleri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Ad");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_Departmanlar", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("DepartmanId");

                    b.Property<string>("DoktorAd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("Ad");

                    b.Property<string>("DoktorSoyad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Soyad");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KullaniciHesabiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelefonNumarasi")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("UzmanlikAlani")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciHesabiId")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "AktifMi");

                    b.ToTable("tbl_Doktorlar", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KimlikNumarasi")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("KullaniciHesabiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("KimlikNumarasi")
                        .IsUnique();

                    b.HasIndex("KullaniciHesabiId")
                        .IsUnique();

                    b.ToTable("tbl_Hastalar", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Ilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("tbl_Ilaclar", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.KullaniciHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("tbl_KullaniciHesaplari", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Muayene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoktorDegerlendirmesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoktorNotlari")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HastaSikayeti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MuayeneTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RandevuId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RandevuId")
                        .IsUnique();

                    b.ToTable("tbl_Muayeneler", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.MuayeneTeshisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoktorNotu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MuayeneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeshisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeshisId");

                    b.HasIndex("MuayeneId", "TeshisId")
                        .IsUnique();

                    b.ToTable("tbl_MuayeneTeshisleri", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HastaId")
                        .HasColumnType("integer");

                    b.Property<string>("IptalNedeni")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OlusturanSekreterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanSekreterId");

                    b.HasIndex("DoktorId", "BaslangicZamani")
                        .IsUnique();

                    b.HasIndex("HastaId", "BaslangicZamani")
                        .IsUnique();

                    b.ToTable("tbl_Randevular", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Recete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<string>("GenelNotlar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HastaId")
                        .HasColumnType("integer");

                    b.Property<int>("MuayeneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceteTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MuayeneId")
                        .IsUnique();

                    b.HasIndex("DoktorId", "ReceteTarihi");

                    b.HasIndex("HastaId", "ReceteTarihi");

                    b.ToTable("tbl_Receteler", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.ReceteIcerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IlacId")
                        .HasColumnType("integer");

                    b.Property<string>("KullanimSuresi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KullanimTalimatlari")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IlacId");

                    b.HasIndex("ReceteId");

                    b.ToTable("tbl_ReceteIcerik", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Sekreter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KullaniciHesabiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("KullaniciHesabiId")
                        .IsUnique();

                    b.ToTable("tbl_Sekreterler", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Teshis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeshisAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TeshisKodu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Teshisler", (string)null);
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Doctor", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.KullaniciHesabi", "KullaniciHesabi")
                        .WithOne()
                        .HasForeignKey("HospitalManagement.Entity.Entities.Doctor", "KullaniciHesabiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("KullaniciHesabi");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Hasta", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.KullaniciHesabi", "KullaniciHesabi")
                        .WithOne()
                        .HasForeignKey("HospitalManagement.Entity.Entities.Hasta", "KullaniciHesabiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KullaniciHesabi");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Muayene", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.Randevu", "Randevu")
                        .WithOne()
                        .HasForeignKey("HospitalManagement.Entity.Entities.Muayene", "RandevuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.MuayeneTeshisi", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.Muayene", "Muayene")
                        .WithMany()
                        .HasForeignKey("MuayeneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.Teshis", "Teshis")
                        .WithMany()
                        .HasForeignKey("TeshisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Muayene");

                    b.Navigation("Teshis");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Randevu", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.Doctor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.Sekreter", "OlusturanSekreter")
                        .WithMany()
                        .HasForeignKey("OlusturanSekreterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");

                    b.Navigation("OlusturanSekreter");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Recete", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.Doctor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.Muayene", "Muayene")
                        .WithOne()
                        .HasForeignKey("HospitalManagement.Entity.Entities.Recete", "MuayeneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");

                    b.Navigation("Muayene");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.ReceteIcerik", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.Ilac", "Ilac")
                        .WithMany()
                        .HasForeignKey("IlacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Entity.Entities.Recete", "Recete")
                        .WithMany()
                        .HasForeignKey("ReceteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilac");

                    b.Navigation("Recete");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Sekreter", b =>
                {
                    b.HasOne("HospitalManagement.Entity.Entities.KullaniciHesabi", "KullaniciHesabi")
                        .WithOne()
                        .HasForeignKey("HospitalManagement.Entity.Entities.Sekreter", "KullaniciHesabiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KullaniciHesabi");
                });

            modelBuilder.Entity("HospitalManagement.Entity.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
